export const SET_INFO = 'play/info'
export const SET_LIST = 'play/list'
export const SET_PRAISE = 'play/praise'
export const SET_MODEL = 'play/model'
export const SET_USER = 'play/User'
export const SET_USER_PIC = 'play/UserPic'